apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: VulnerableGoRepo4GHTest
          artifact-id: 3c15671d-e545-475b-9e6d-6501d26e33d4
          target-environment: Pre-Prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: nodes
          artifact-id: 8a7eb3a5-6720-48e1-a883-beafbd23ad12
          target-environment: Pre-Prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: prodvuln
          artifact-id: 1f317202-3fb5-4033-b8a1-0dec14b11f31
          target-environment: Pre-Prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: jo
          artifact-id: ded1934b-c3b9-441c-9568-0d260ec955fd
          target-environment: Pre-Prod
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: nodejasaspm
          artifact-id: 0004e609-ba1a-45d0-8870-cfb2f9138bdf
          target-environment: Pre-Prod